--- 
title: "OMM report"
author: "Philipp C. Muench"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: scrbook
link-citations: yes
colorlinks: yes
graphics: yes
lot: yes
lof: yes
toc-depth: 2
fontsize: 11pt
mainfont: Palatino
monofont: "Source Code Pro"
monofontoptions: "Scale=0.8"
css: style.css
outputbo:
  bookdown::gitbook:
    css: style.css
    config:
      sharing: null
      toc:
        collapse: section
      fontsettings:
        theme: white
        family: Source Code Pro
        size: 2
---

```{r setup, include=FALSE}
set.seed(0728)
knitr::opts_chunk$set(tidy = TRUE)
if (knitr::is_html_output()) {
  # ignore percentage widths for HTML output, unless they are used for mutiple
  # figures side by side
  knitr::opts_hooks$set(out.width = function(options) {
    if (options$fig.show != "hold" && grepl("%$", options$out.width)) {
      options$out.width <- NULL
    }
    options
  })
}
```

# Setup {#Setup}

## Installation 
```{r, eval = F}
devtools::install_github(repo="knausb/vcfR") # removed from CRAN
devtools::install_github("jokergoo/ComplexHeatmap")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("rtracklayer")
install.packages("rmdformats")
install.packages("ggplot2")
install.packages("reshape2")
install.packages("ggridges")
install.packages("data.table")
install.packages("knitr")
install.packages("kableExtra")
install.packages("plotly")
install.packages("DT")
install.packages("circlize")
install.packages("ComplexHeatmap")
install.packages("rtracklayer")
install.packages("bookdown")
install.packages("XML")
install.packages("randomcoloR")
install.packages("ggrepel")
devtools::install_github(repo="omegahat/XML") # needs `brew install libxml2` on macos
```

```{r, results="hide"}
rm(list = ls())
source("utils.R")
library("vcfR")
library("rmdformats")
library("ggplot2")
library("reshape2")
library("ggridges")
library("data.table")
library("knitr")
library("kableExtra")
library("plotly")
library("DT")
library("circlize")
library("ComplexHeatmap")
library("rtracklayer")
library("ggrepel")
library("randomcoloR")
library("bookdown")
```

## Generate report

```{r, eval=FALSE}
setwd("~/ActiveProjects/OligoMM-report")
bookdown::serve_book(getwd())
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), "bookdown", "knitr", "rmarkdown"
), "packages.bib")
```

_Note:_ for `rtracklayer` you might need _curl_
```{bash, eval = F}
sudo apt-get install libcurl4-openssl-dev
```

You need to install [Pandoc](https://pandoc.org/installing.html). 




```{r, eval=FALSE}
servr::daemon_stop(1)
```

This will starts a browser window pointing to [http://127.0.0.1:7853](http://127.0.0.1:7853) presenting the report written in [R Markdown](https://rmarkdown.rstudio.com/) and will update as soon as there are changes on `.Rmd` files in the workspace.
